# <span style="color: blue;">Taller numpy</span>

## <span style="color: blue;">Autor</span>

* Johan Stevan Sáenz Robayo.

## Contenido
* ¿Qué es ?
  * ¿Por qué usar arrays de numpy y no listas o tuplas de python?
* Creación básica de arrays
* Indexación básica 
* Diferentes tipos de datos en los arrays
* Forma de los arrays
  * Reformar arrays
  * Dimensión desconocida
  * Transpuesta
* Iterar arrays
* Aplicar operaciones entre arrays
  * Suma
  * Multiplicación 
  * Multiplicación matricial

## <span style="color: blue;">¿Qué es?</span>
  
Numpy es un paquete con base en python, para manejo de conjuntos o "arrays".


### <span style="color: blue;">¿Por qué usar arrays de numpy y no listas o tuplas de python?</span>

Usar arrays gasta menos memoria.

In [1]:
# Importando numpy
import numpy as np 

## <span style="color: blue;">Creación básica de arrays</span>
Se pueden crear arrays de diferentes dimensiones, usando números, listas o tuplas.

In [23]:
a=np.array("Hola") #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4,],[5,6,7,8,]]) #arrar de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3
e=np.array([[[[1,2], [3,4]]],[[[5,6], [7,8]]]]) #array de dismensión 4

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")
print("e =",e,"\n")

a = Hola 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

e = [[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]] 



Para verificar la dimensionalidad se usa `ndim`

In [24]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


## <span style="color: blue;">Indexación básica</span>
La indexación en numpy es similar a las lsitas de python, el conteo empiza desde 0. Cada número implica buscar en la posicioón en cada dimensión del array

In [25]:
print("a =",a)
print("b[2] = ",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])
print("e[0] =",e[0])

a = Hola
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]
e[0] = [[[1 2]
  [3 4]]]


In [40]:
print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("d[1,0,2] =",d[1,0,2])
print("e[0,0,0,1] =",  e[0,0,0,1])

a = Hola
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11
e[0,0,0,1] = 2


se pueden segmentar los *arrays* como las listas de python.

In [41]:
print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


## <span style="color: blue;">Diferentes tipos de datos en los arrays</span>

Los arrays también pueden tener cadenas (carácteres), booleanos y punto flotante.

In [42]:
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)

<U7


Se pueden manipulas los arrays con la función creadora de array `np.array`, desde que el cambio sea posible, como parar de enteros a carácteres, pero no viceversa.

In [44]:
number_to_string=np.array([6,1,2,4,623,8, "a"], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8' b'a']


In [49]:
try:
    error_array = np.array([1,2, "a"], dtype='i')
except:
    print("hay un error en su lógica, no todos son enteros")

hay un error en su lógica, no todos son enteros


Tambien se puede cambiar el tipon de los arrays

In [54]:
floating_array = np.array([1.1343, 2.1311, 3.13643, 4.255]) #punto flotante

int_array = floating_array.astype('i')
str_array = floating_array.astype("S")
print(int_array)
print(str_array)

[1 2 3 4]
[b'1.1343' b'2.1311' b'3.13643' b'4.255']
b'3.13643'


## <span style="color: blue;">Forma de los arrys</span>
La forma es distinta a la dimensión. Esta se define como el número de elementos de la dimensión.

In [55]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 
print(e.shape) # e = [[[[1 2] [3 4]]] [[[5 6] [7 8]]]] 

()
(4,)
(2, 4)
(2, 2, 4)
(2, 1, 2, 2)


### <span style="color: blue;">Reformar arrys</span>
Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión.

In [66]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,1,1,2)
print("c_4D =",c_4D,"\n")

print(c_4D.ndim)


c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[[[1 2]]]


 [[[3 4]]]


 [[[5 6]]]


 [[[7 8]]]] 

4


¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [67]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


`d` es un array con 16 elementos, así que podemos hacer reshape con tamaños por ejemplo 1x16, 4x4, 8x2, 2x4x2 Por ejemplo, no podemos reformar un array a 3x5.

In [68]:
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones, dimensiones no coinciden')

Hay un error en sus operaciones, dimensiones no coinciden


In [72]:
d1=d.reshape(2,2,2,2)
print("d1 =", d1)
print("dimensión de d =",d.ndim)
print("dimensión de d1 =",d1.ndim)

d1 = [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
dimensión de d = 3
dimensión de d1 = 4


### <span style="color: blue;">Dimensión desconocida</span>
podemos definir el cambio de la forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de denir el tamaño que mejor se ajuste.

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos usar la dimensión desconocida para "aplanar" el array a una dimensión.

In [76]:
d2=d.reshape(-1)
print(d2)
print("La dimensión es",d2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
La dimensión es 1


### <span style="color: blue;">Transpuesta</span>
Para transponer arrays se utiliza `.T`. 

In [80]:
print("d =",d,"\n")
print("d.T =",d.T, "\n")

print("c =",c,"\n")
print("c.T =",c.T)

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.T = [[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]] 

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## <span style="color: blue;">Iterar arrays</span>
Podemos usar los métodos tradicionales para iterar.

In [83]:
for x in e:
    print(x)

[[[1 2]
  [3 4]]]
[[[5 6]
  [7 8]]]


Si queremos iterar cada elemento, necesitamos un `for` por cada dimensión

In [86]:
for x in e:
    for y in x:
        for z in y:
            for k in z:
                print(k)

1
2
3
4
5
6
7
8


Esto Por supuesto no es óptimo. Para ello numpy tiene la función `nditer()` para estos casos.

In [87]:
for x in np.nditer(e):
    print(x)

1
2
3
4
5
6
7
8


## <span style="color: blue;">Aplicar operaciones entre arrays</span>
*numpy* tiene sus propias formas de aplicar operaciones:

### <span style="color: blue;">Suma</span>
*numpy* tiene dos funciones, `np.add()` y `np.sum`. El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma.

In [88]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [90]:
arr3=np.array([[2,2,2],[2,2,2]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
54


Si aplicamos un eje en `np.sum()`, se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtiene los mismos resultados que `np.add()`.

In [99]:
np.sum([arr1,arr2],axis=0)

array([[7, 7, 7],
       [7, 7, 7]])

In [100]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [4, 4, 4]])

### <span style="color: blue;">Multiplicación</span>
El primer caso de multiplicación es `np.prod()`, que funciona similar que `np.sum()` 

In [101]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


### <span style="color: blue;">Multiplicación Matricial</span>
Para la multiplicación de matrices usamos `np.matmul()` o `np.dot()`. Hay que tener en cuenta la dorma de las matrices

In [109]:
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [110]:
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan igual con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [111]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [112]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con *matmul* no se pueden multiplicar escalares c.A (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con dot, donde este toma los números dentro de las matrices como elementos.

In [113]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])